version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - blog:/data/blogdata
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "nc", "-z", "mongodb", "27017"]
      interval: 30s
      timeout: 10s
      retries: 5

  blog_backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app

volumes:
  blog:
